apiVersion: v1
kind: Service
metadata:
  name: {{ include "clowder2.fullname" . }}-frontend
  labels:
    {{- include "clowder2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "clowder2.fullname" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
