repos:
  - repo: local
    hooks:
      - id: extract-openapi
        name: extract-openapi
        entry: pipenv run extract-openapi
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: generate-frontend-api-client
        name: generate-frontend-api-client
        entry: bash -c 'cd frontend && npm run codegen:v2:file'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "cd frontend && npx eslint --fix src"
        language: system
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c "cd frontend && npx prettier src --write"
        language: system
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ "--profile=black" ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: deployments/kubernetes/charts
      - id: end-of-file-fixer
        exclude: 'openapi.json|frontend/src/openapi/v2/'
      - id: trailing-whitespace
        exclude: 'openapi.json|frontend/src/openapi/v2/'
#  - repo: https://github.com/shellcheck-py/shellcheck-py
#    rev: v0.10.0.1
#    hooks:
#      - id: shellcheck
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
