repos:
  - repo: local
    hooks:
      - id: extract-openapi
        name: extract-openapi
        entry: python backend/extract-openapi.py app.main:app
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: generate-frontend-api-client
        name: generate-frontend-api-client
        entry: bash -c 'cd frontend && npm run codegen:v2:file'
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "cd frontend && npx eslint --fix src"
        language: system
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: bash -c "cd frontend && npx prettier src --write"
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        exclude: deployments/kubernetes/charts
      - id: end-of-file-fixer
        exclude: 'openapi.json|frontend/src/openapi/v2/'
      - id: trailing-whitespace
        exclude: 'openapi.json|frontend/src/openapi/v2/'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
