---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clowder2-geoserver-pv
  labels:
    name: clowder2-geoserver
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /radiant/projects/bbfa/clowder2/geoserver
    server: radiant-nfs.ncsa.illinois.edu
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  selector:
    matchLabels:
      name: clowder2-geoserver
---
