import * as V1 from "./v1";
import * as V2 from "./v2";

/*
 * Generated OpenAPI clients for Clowder.
 *
 * These V1, V2, etc modules are automatically generated by openapi-typescript-codegen.
 * You should NEVER modify these files manually. Instead, modify the swagger spec offered
 * by the Clowder API, then regenerate these files from the new spec.
 *
 * These modules can be regenerated by running `npm run codegen` at the project root.
 *
 */

export { V1, V2 };
