apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clowder2.fullname" . }}-heartbeat
  labels:
    {{- include "clowder2.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clowder2.fullname" . }}-heartbeat
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "clowder2.fullname" . }}-heartbeat
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: extractors-heartbeat
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.heartbeat.image.repository }}:{{ .Values.heartbeat.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.heartbeat.image.pullPolicy }}
          env:
            - name: MONGODB_URL
              value: {{ .Values.heartbeat.env.MONGODB_URL }}
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.auth.username }}
            - name: RABBITMQ_PASS
              {{- if .Values.heartbeat.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{.Values.heartbeat.existingSecret }}
                  key: {{.Values.heartbeat.existingRabbitMQSecretKey | default "rabbitmq-password" }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{include "clowder2.fullname" . }}-rabbitmq
                  key: rabbitmq-password
              {{- end }}
            - name: RABBITMQ_HOST
              value: {{ .Values.heartbeat.env.RABBITMQ_HOST }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
